from CommonTonePitchInscriber import CommonTonePitchInscriber
from MockPitchInscriber import MockPitchInscriber
from PitchInscriber import PitchInscriber
from RandomPitchInscriber import RandomPitchInscriber
from ShepherdTonePitchInscriber import ShepherdTonePitchInscriber
from ShiftingHarmonyPitchInscriber import ShiftingHarmonyPitchInscriber
from SingleHarmonyPitchInscriber import SingleHarmonyPitchInscriber
